### ISSUE TITLE
PlayerLoaded | Configuration Value

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [PetrisGR/FiveM-BriefcaseMission#5]
If not using ESX what should we put here?

```
PlayerLoaded = "esx:playerLoaded" -- add your client event name which defines player's load into the server.
```

**Comment by PetrisGR** [comment]
You'll need to set an event, triggered when the player is loaded into the server. This value is important, otherwise, the script won't work properly (Players connecting will not get the latest state of the event and if it's already started, they can't take part/Players connecting will not load props used upon their connection). Could you tell me which framework are you using so I can find the right event?

**Comment by Legacy-TacticalGamingInteractive** [comment]
I dont use a framework persay. Its completely standalone. Most of our scripts start by a marker placed on the map or maybe a command.

The only stuff we run are portions of NDFramework or ND_Core (functions, exports and events can be found at https://ndfw.gitbook.io/nd-framework/developers/client if it helps) and some stuff by ox like oxmysql, ox_lib etc.

**Comment by Legacy-TacticalGamingInteractive** [comment]
Since we are in this issue I can also mention

```
SCRIPT ERROR: @BriefcaseMission/client/petris_cl.lua:27: attempt to call a nil value (method 'LoadAnimDict')^7
@BriefcaseMission/client/petris_cl.lua^7:27)
```

**Comment by PetrisGR** [comment]
> Since we are in this issue I can also mention
> 
> ```
> SCRIPT ERROR: @BriefcaseMission/client/petris_cl.lua:27: attempt to call a nil value (method 'LoadAnimDict')^7
> @BriefcaseMission/client/petris_cl.lua^7:27)
> ```

Please create another issue for this problem so we can't complicate things for others that may face the same issues.

**Comment by PetrisGR** [comment]
> I dont use a framework persay. Its completely standalone. Most of our scripts start by a marker placed on the map or maybe a command.
> 
> The only stuff we run are portions of NDFramework or ND_Core (functions, exports and events can be found at https://ndfw.gitbook.io/nd-framework/developers/client if it helps) and some stuff by ox like oxmysql, ox_lib etc.
> 
> On the note of ND_Core I was thinking if trying to use the export for addMoney to reward players with your script.

You can use ND_Core's addMoney event/function in the server configuration if you want.

As for the playerLoaded event, you can put this code anywhere (even in other scripts), so the pre-configured "esx:playerLoaded" event will get triggered once the player loads into the server.

```
local playerJustConnected = true

AddEventHandler('playerSpawned', function()
    Citizen.Wait(5000) -- Safe interval to let the player load
    if playerJustConnected then
        TriggerEvent('esx:playerLoaded')
        playerJustConnected = false
    end
end)
```

**Comment by PetrisGR** [comment]
@Legacy-TacticalGamingInteractive Did that resolve your issue?

**Comment by PetrisGR** [comment]
`Closing the issue, due to getting no response within 48 hours.`
