### ISSUE TITLE
Nil Value (LoadAnimDict) | Client Script Error

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [PetrisGR/FiveM-BriefcaseMission#6]
```
SCRIPT ERROR: @BriefcaseMission/client/petris_cl.lua:27: attempt to call a nil value (method 'LoadAnimDict')^7
@BriefcaseMission/client/petris_cl.lua^7:27)
```

**Comment by PetrisGR** [comment]
This error did not appear while I was testing it. Have you made any modifications to the script? It seems that this function exists `client/petris_cl.lua:358` and it is not nil. Make sure you haven't made any changes to the function located there. Re-downloading the script may fix your issue.

**Comment by Legacy-TacticalGamingInteractive** [comment]
I haven't made any modifications there this is straight from the download running latest artifacts and 2699 game version
My file says

Line 27
```
    BriefcaseMissionFunctions:LoadAnimDict(Petris_ClientConfig["Animation"].Dictionary)
    ```
   
   Line 358 
    ```
    function BriefcaseMissionFunctions:LoadAnimDict(dict)
    RequestAnimDict(dict)
    while not HasAnimDictLoaded(dict) do
        Citizen.Wait(1)
    end
end
```

**Comment by PetrisGR** [comment]
It seems good. Please make sure the function's table exists. Also, make sure you have not merged any other resource with it.

[Line 18 | Function's Table](https://github.com/PetrisGR/FiveM-BriefcaseMission/blob/98dd083d914f030677c0fbb6ef292e10e958733e/client/petris_cl.lua#L18)

**Comment by PetrisGR** [comment]
By the way, could you let me know when this error appears?

**Comment by PetrisGR** [comment]
By the way, I wanted to know when this script error occurs. Is it when you start the script or when the mission is started?

**Comment by Legacy-TacticalGamingInteractive** [comment]
> By the way, I wanted to know when this script error occurs. Is it when you start the script or when the mission is started?

Its happening upon loading into server. I have not even started mission yet but its already there.

Yes line 18 exists


I ALSO SEE


![image](https://user-images.githubusercontent.com/25211271/210684488-1a933ddc-88b0-4e0e-bb1f-35ca6140c09e.png)

**Comment by PetrisGR** [comment]
Yeah, that's the configuration value of the PlayerLoaded event and might also affect the error below. It's showing up because you may have modified the configuration value of the PlayerLoaded event. Could you show me your configuration file?

**Comment by Legacy-TacticalGamingInteractive** [comment]
I've reset my config and the mission starts now! However now there is yet another bug unless I'm clueless. The briefcase was supposedly up on the hill near the vinewood sign but I walked all around that area and couldn't find it in the circle at all?

**Comment by PetrisGR** [comment]
You can check out the pre-configured coordinates for the briefcase. It's hidden well 😛. Also, about the new error, please create a new issue, and I can assist you there when I am available.
