### ISSUE TITLE
How to start mission ? 

### ISSUE THREAD

**Issue by allyaminou** [PetrisGR/FiveM-BriefcaseMission#8]
Hi, trying to get the mission to start but not sure how to do it. Could you give me some details how to start it ?

**Comment by PetrisGR** [comment]
Hello, you can start this by adding some random times in the "PossibleTimes" value like the examples.
You can find this configuration value here: https://github.com/PetrisGR/FiveM-BriefcaseMission/blob/98dd083d914f030677c0fbb6ef292e10e958733e/configuration/petris_config_sv.lua#L15

You can also start this manually which is a more advanced step or for testing purposes. You can find the exports in README.md!
